var Bezier=function(z){function r(n){if(w[n])return w[n].exports;var p=w[n]={exports:{},id:n,loaded:!1};return z[n].call(p.exports,p,p.exports,r),p.loaded=!0,p.exports}var w={};return r.m=z,r.c=w,r.p="",r(0)}([function(z,r,w){z.exports=w(1)},function(z,r,w){var n="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(p){return typeof p}:function(p){return p&&"function"==typeof Symbol&&p.constructor===Symbol?"symbol":typeof p};!function(){function p(a,b,d,c,e){"undefined"==typeof e&&
(e=.5);var h=k.projectionratio(e,a),g=1-h;b={x:h*b.x+g*c.x,y:h*b.y+g*c.y};a=k.abcratio(e,a);return{A:{x:d.x+(d.x-b.x)/a,y:d.y+(d.y-b.y)/a},B:d,C:b}}var m=Math.abs,G=Math.min,u=Math.max,r=Math.cos,A=Math.sin,C=Math.acos,B=Math.sqrt,D=Math.PI,y={x:0,y:0,z:0},k=w(2),F=w(3),l=function(a){var b=a&&a.forEach?a:[].slice.call(arguments),d=!1;if("object"===n(b[0])){d=b.length;var c=[];b.forEach(function(a){["x","y","z"].forEach(function(b){"undefined"!=typeof a[b]&&c.push(a[b])})});b=c}var e=!1,f=b.length;
if(d){if(4<d){if(1!==arguments.length)throw Error("Only new Bezier(point[]) is accepted for 4th and higher order curves");e=!0}}else if(6!==f&&8!==f&&9!==f&&12!==f&&1!==arguments.length)throw Error("Only new Bezier(point[]) is accepted for 4th and higher order curves");this._3d=d=!e&&(9===f||12===f)||a&&a[0]&&"undefined"!=typeof a[0].z;e=[];for(var g=0,q=d?3:2;f>g;g+=q){var l={x:b[g],y:b[g+1]};d&&(l.z=b[g+2]);e.push(l)}this.order=e.length-1;this.points=e;b=["x","y"];d&&b.push("z");this.dims=b;this.dimlen=
b.length;(function(a){var b=a.points;b=k.align(b,{p1:b[0],p2:b[a.order]});for(var d=0;d<b.length;d++)if(1E-4<m(b[d].y))return void(a._linear=!1);a._linear=!0})(this);this._t1=0;this._t2=1;this.update()};l.fromSVG=function(a){var b=a.match(/[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?/g).map(parseFloat);return/[cq]/.test(a)?(b=b.map(function(a,c){return 2>c?a:a+b[c%2]}),new l(b)):new l(b)};l.quadraticFromPoints=function(a,b,d,c){if("undefined"==typeof c&&(c=.5),0===c)return new l(b,b,d);if(1===c)return new l(a,
b,b);b=p(2,a,b,d,c);return new l(a,b.A,d)};l.cubicFromPoints=function(a,b,d,c,e){"undefined"==typeof c&&(c=.5);var h=p(3,a,b,d,c);"undefined"==typeof e&&(e=k.dist(b,h.C));var g=e*(1-c)/c,q=k.dist(a,d),H=(d.x-a.x)/q;q=(d.y-a.y)/q;h=h.A;return new l(a,{x:a.x+(h.x+(b.x-e*H-h.x)/(1-c)-a.x)/c,y:a.y+(h.y+(b.y-e*q-h.y)/(1-c)-a.y)/c},{x:d.x+(h.x+(b.x+g*H-h.x)/c-d.x)/(1-c),y:d.y+(h.y+(b.y+g*q-h.y)/c-d.y)/(1-c)},d)};var c=function(){return k};l.getUtils=c;l.prototype={getUtils:c,valueOf:function(){return this.toString()},
toString:function(){return k.pointsToString(this.points)},toSVG:function(a){if(this._3d)return!1;a=this.points;for(var b=["M",a[0].x,a[0].y,2===this.order?"Q":"C"],d=1,c=a.length;c>d;d++)b.push(a[d].x),b.push(a[d].y);return b.join(" ")},update:function(){this.dpoints=[];for(var a=this.points,b=a.length,d=b-1;1<b;b--,d--){for(var c,e=[],f=0;d>f;f++)c={x:d*(a[f+1].x-a[f].x),y:d*(a[f+1].y-a[f].y)},this._3d&&(c.z=d*(a[f+1].z-a[f].z)),e.push(c);this.dpoints.push(e);a=e}this.computedirection()},computedirection:function(){var a=
this.points;this.clockwise=0<k.angle(a[0],a[this.order],a[1])},length:function(){return k.length(this.derivative.bind(this))},_lut:[],getLUT:function(a){if(a=a||100,this._lut.length===a)return this._lut;this._lut=[];for(var b=0;a>=b;b++)this._lut.push(this.compute(b/a));return this._lut},on:function(a,b){b=b||5;for(var d,c=this.getLUT(),e=[],f=0,g=0;g<c.length;g++)d=c[g],k.dist(d,a)<b&&(e.push(d),f+=g/c.length);return e.length?f/e.length:!1},project:function(a){var b=this.getLUT(),d=b.length-1,c=
k.closest(b,a);b=c.mdist;var e=c.mpos;if(0===e||e===d)return d=e/d,a=this.compute(d),a.t=d,a.d=b,a;c=(e+1)/d;var f=.1/d;b+=1;for(e=d=(e-1)/d;c+f>d;d+=f){var g=this.compute(d);var q=k.dist(a,g);b>q&&(b=q,e=d)}return g=this.compute(e),g.t=e,g.d=b,g},get:function(a){return this.compute(a)},point:function(a){return this.points[a]},compute:function(a){if(0===a)return this.points[0];if(1===a)return this.points[this.order];var b=this.points,d=1-a;if(1===this.order)return k={x:d*b[0].x+a*b[1].x,y:d*b[0].y+
a*b[1].y},this._3d&&(k.z=d*b[0].z+a*b[1].z),k;if(4>this.order){var c,e,f;k=d*d;var g=a*a,q=0;2===this.order?(b=[b[0],b[1],b[2],y],c=k,e=d*a*2,f=g):3===this.order&&(c=k*d,e=k*a*3,f=d*g*3,q=a*g);var k={x:c*b[0].x+e*b[1].x+f*b[2].x+q*b[3].x,y:c*b[0].y+e*b[1].y+f*b[2].y+q*b[3].y};return this._3d&&(k.z=c*b[0].z+e*b[1].z+f*b[2].z+q*b[3].z),k}for(b=JSON.parse(JSON.stringify(this.points));1<b.length;){for(d=0;d<b.length-1;d++)b[d]={x:b[d].x+(b[d+1].x-b[d].x)*a,y:b[d].y+(b[d+1].y-b[d].y)*a},"undefined"!=typeof b[d].z&&
(b[d]=b[d].z+(b[d+1].z-b[d].z)*a);b.splice(b.length-1,1)}return b[0]},raise:function(){var a,b=this.points,d=[b[0]],c=b.length;for(a=1;c>a;a++){var e=b[a];var f=b[a-1];d[a]={x:(c-a)/c*e.x+a/c*f.x,y:(c-a)/c*e.y+a/c*f.y}}return d[c]=b[c-1],new l(d)},derivative:function(a){var b,d,c=1-a,e=0,f=this.dpoints[0];2===this.order&&(f=[f[0],f[1],y],b=c,d=a);3===this.order&&(b=c*c,d=c*a*2,e=a*a);a={x:b*f[0].x+d*f[1].x+e*f[2].x,y:b*f[0].y+d*f[1].y+e*f[2].y};return this._3d&&(a.z=b*f[0].z+d*f[1].z+e*f[2].z),a},
inflections:function(){return k.inflections(this.points)},normal:function(a){return this._3d?this.__normal3(a):this.__normal2(a)},__normal2:function(a){a=this.derivative(a);var b=B(a.x*a.x+a.y*a.y);return{x:-a.y/b,y:a.x/b}},__normal3:function(a){var b=this.derivative(a);a=this.derivative(a+.01);var d=B(b.x*b.x+b.y*b.y+b.z*b.z),c=B(a.x*a.x+a.y*a.y+a.z*a.z);b.x/=d;b.y/=d;b.z/=d;a.x/=c;a.y/=c;a.z/=c;d=a.y*b.z-a.z*b.y;c=a.z*b.x-a.x*b.z;a=a.x*b.y-a.y*b.x;var e=B(d*d+c*c+a*a);d/=e;c/=e;a/=e;a=[d*d,d*c-
a,d*a+c,d*c+a,c*c,c*a-d,d*a-c,c*a+d,a*a];return{x:a[0]*b.x+a[1]*b.y+a[2]*b.z,y:a[3]*b.x+a[4]*b.y+a[5]*b.z,z:a[6]*b.x+a[7]*b.y+a[8]*b.z}},hull:function(a){var b=this.points,d=[],c=0,e;d[c++]=b[0];d[c++]=b[1];d[c++]=b[2];for(3===this.order&&(d[c++]=b[3]);1<b.length;){var f=[];var g=0;for(e=b.length-1;e>g;g++){var q=k.lerp(a,b[g],b[g+1]);d[c++]=q;f.push(q)}b=f}return d},split:function(a,b){if(0===a&&b)return this.split(b).left;if(1===b)return this.split(a).right;var d=this.hull(a);d={left:new l(2===
this.order?[d[0],d[3],d[5]]:[d[0],d[4],d[7],d[9]]),right:new l(2===this.order?[d[5],d[4],d[2]]:[d[9],d[8],d[6],d[3]]),span:d};if(d.left._t1=k.map(0,0,1,this._t1,this._t2),d.left._t2=k.map(a,0,1,this._t1,this._t2),d.right._t1=k.map(a,0,1,this._t1,this._t2),d.right._t2=k.map(1,0,1,this._t1,this._t2),!b)return d;b=k.map(b,a,1,0,1);return d.right.split(b).left},extrema:function(){var a,b,d={},c=[];return this.dims.forEach(function(e){b=function(a){return a[e]};a=this.dpoints[0].map(b);d[e]=k.droots(a);
3===this.order&&(a=this.dpoints[1].map(b),d[e]=d[e].concat(k.droots(a)));d[e]=d[e].filter(function(a){return 0<=a&&1>=a});c=c.concat(d[e].sort())}.bind(this)),c=c.sort().filter(function(a,b){return c.indexOf(a)===b}),d.values=c,d},bbox:function(){var a=this.extrema(),b={};return this.dims.forEach(function(d){b[d]=k.getminmax(this,d,a[d])}.bind(this)),b},overlaps:function(a){var b=this.bbox();a=a.bbox();return k.bboxoverlap(b,a)},offset:function(a,b){if("undefined"!=typeof b){var d=this.get(a),c=this.normal(a),
e={c:d,n:c,x:d.x+c.x*b,y:d.y+c.y*b};return this._3d&&(e.z=d.z+c.z*b),e}if(this._linear){var f=this.normal(0);d=this.points.map(function(b){var d={x:b.x+a*f.x,y:b.y+a*f.y};return b.z&&c.z&&(d.z=b.z+a*f.z),d});return[new l(d)]}return this.reduce().map(function(b){return b.scale(a)})},simple:function(){if(3===this.order){var a=k.angle(this.points[0],this.points[3],this.points[1]),b=k.angle(this.points[0],this.points[3],this.points[2]);if(0<a&&0>b||0>a&&0<b)return!1}a=this.normal(0);b=this.normal(1);
var d=a.x*b.x+a.y*b.y;this._3d&&(d+=a.z*b.z);a=m(C(d));return D/3>a},reduce:function(){var a,b=0,d=0,c=[],e=[],f=this.extrema().values;-1===f.indexOf(0)&&(f=[0].concat(f));-1===f.indexOf(1)&&f.push(1);b=f[0];for(a=1;a<f.length;a++){d=f[a];var g=this.split(b,d);g._t1=b;g._t2=d;c.push(g);b=d}return c.forEach(function(a){for(d=b=0;1>=d;)for(d=b+.01;1.01>=d;d+=.01)if(g=a.split(b,d),!g.simple()){if(d-=.01,.01>m(b-d))return[];g=a.split(b,d);g._t1=k.map(b,0,1,a._t1,a._t2);g._t2=k.map(d,0,1,a._t1,a._t2);
e.push(g);b=d;break}1>b&&(g=a.split(b,1),g._t1=k.map(b,0,1,a._t1,a._t2),g._t2=a._t2,e.push(g))}),e},scale:function(a){var b=this.order,d=!1;if("function"==typeof a&&(d=a),d&&2===b)return this.raise().scale(d);var c=this.clockwise,e=d?d(0):a,f=d?d(1):a,g=[this.offset(0,10),this.offset(1,10)],q=k.lli4(g[0],g[0].c,g[1],g[1].c);if(!q)throw Error("cannot scale this curve. Try reducing it first.");var m=this.points,E=[];return[0,1].forEach(function(a){var d=E[a*b]=k.copy(m[a*b]);d.x+=(a?f:e)*g[a].n.x;d.y+=
(a?f:e)*g[a].n.y}.bind(this)),d?([0,1].forEach(function(e){if(2!==this.order||!e){var f=m[e+1],g=f.x-q.x,h=f.y-q.y,k=d?d((e+1)/b):a;d&&!c&&(k=-k);var l=B(g*g+h*h);E[e+1]={x:f.x+g/l*k,y:f.y+h/l*k}}}.bind(this)),new l(E)):([0,1].forEach(function(a){if(2!==this.order||!a){var d=E[a*b],c=this.derivative(a);E[a+1]=k.lli4(d,{x:d.x+c.x,y:d.y+c.y},q,m[a+1])}}.bind(this)),new l(E))},outline:function(a,b,d,c){function e(a,b,d,c,e){return function(f){var g=b-a;return k.map(f,0,1,a+c/d*g,a+(c+e)/d*g)}}b="undefined"==
typeof b?a:b;var f,g=this.reduce(),h=g.length,l=[],m=[],p=0,t=this.length(),x="undefined"!=typeof d&&"undefined"!=typeof c;g.forEach(function(f){n=f.length();x?(l.push(f.scale(e(a,d,t,p,n))),m.push(f.scale(e(-b,-c,t,p,n)))):(l.push(f.scale(a)),m.push(f.scale(-b)));p+=n});m=m.map(function(a){return f=a.points,f[3]?a.points=[f[3],f[2],f[1],f[0]]:a.points=[f[2],f[1],f[0]],a}).reverse();g=l[h-1].points[l[h-1].points.length-1];var v=m[0].points[0];h=k.makeline(m[h-1].points[m[h-1].points.length-1],l[0].points[0]);
g=k.makeline(g,v);h=[h].concat(l).concat([g]).concat(m);var n=h.length;return new F(h)},outlineshapes:function(a,b,d){a=this.outline(a,b||a).curves;b=[];for(var c=1,e=a.length;e/2>c;c++){var f=k.makeshape(a[c],a[e-c],d);f.startcap.virtual=1<c;f.endcap.virtual=e/2-1>c;b.push(f)}return b},intersects:function(a,b){return a?a.p1&&a.p2?this.lineIntersects(a):(a instanceof l&&(a=a.reduce()),this.curveintersects(this.reduce(),a,b)):this.selfintersects(b)},lineIntersects:function(a){var b=G(a.p1.x,a.p2.x),
d=G(a.p1.y,a.p2.y),c=u(a.p1.x,a.p2.x),e=u(a.p1.y,a.p2.y),f=this;return k.roots(this.points,a).filter(function(a){a=f.get(a);return k.between(a.x,b,c)&&k.between(a.y,d,e)})},selfintersects:function(a){var b,d=this.reduce(),c=d.length-2,e=[];for(b=0;c>b;b++){var f=d.slice(b,b+1);var g=d.slice(b+2);f=this.curveintersects(f,g,a);e=e.concat(f)}return e},curveintersects:function(a,b,d){var c=[];a.forEach(function(a){b.forEach(function(b){a.overlaps(b)&&c.push({left:a,right:b})})});var e=[];return c.forEach(function(a){a=
k.pairiteration(a.left,a.right,d);0<a.length&&(e=e.concat(a))}),e},arcs:function(a){return this._iterate(a||.5,[])},_error:function(a,b,d,c){var e=(c-d)/4;d=this.get(d+e);c=this.get(c-e);b=k.dist(a,b);d=k.dist(a,d);a=k.dist(a,c);return m(d-b)+m(a-b)},_iterate:function(a,b){var d=0;do{var c=0;var e=1;var f,g=this.get(d),q=!1,l=1,m=0;do{var p=q;var t=v;var n=(d+e)/2;m++;var v=this.get(n);var u=this.get(e);v=k.getccenter(g,v,u);v.interval={start:d,end:e};u=this._error(v,g,d,e);if(q=a>=u,f=p&&!q,f||(l=
e),q){if(1<=e){if(v.interval.end=l=1,t=v,1<e)d={x:v.x+v.r*r(v.e),y:v.y+v.r*A(v.e)},v.e+=k.angle({x:v.x,y:v.y},d,this.get(1));break}e+=(e-d)/2}else e=n}while(!f&&100>c++);if(100<=c)break;t=t?t:v;b.push(t);d=l}while(1>e);return b}};z.exports=l}()},function(z,r,w){!function(){var n=Math.abs,p=Math.cos,m=Math.sin,G=Math.acos,u=Math.atan2,r=Math.sqrt,A=Math.pow,C=function(c){return 0>c?-A(-c,1/3):A(c,1/3)},B=Math.PI,D=2*B,y=B/2,k=Number.MAX_SAFE_INTEGER,F=Number.MIN_SAFE_INTEGER,l={Tvalues:[-.06405689286260563,
.06405689286260563,-.1911188674736163,.1911188674736163,-.3150426796961634,.3150426796961634,-.4337935076260451,.4337935076260451,-.5454214713888396,.5454214713888396,-.6480936519369755,.6480936519369755,-.7401241915785544,.7401241915785544,-.820001985973903,.820001985973903,-.8864155270044011,.8864155270044011,-.9382745520027328,.9382745520027328,-.9747285559713095,.9747285559713095,-.9951872199970213,.9951872199970213],Cvalues:[.12793819534675216,.12793819534675216,.1258374563468283,.1258374563468283,
.12167047292780339,.12167047292780339,.1155056680537256,.1155056680537256,.10744427011596563,.10744427011596563,.09761865210411388,.09761865210411388,.08619016153195327,.08619016153195327,.0733464814110803,.0733464814110803,.05929858491543678,.05929858491543678,.04427743881741981,.04427743881741981,.028531388628933663,.028531388628933663,.0123412297999872,.0123412297999872],arcfn:function(c,a){var b=a(c),d=b.x*b.x+b.y*b.y;return"undefined"!=typeof b.z&&(d+=b.z*b.z),r(d)},between:function(c,a,b){return c>=
a&&b>=c||l.approximately(c,a)||l.approximately(c,b)},approximately:function(c,a,b){return n(c-a)<=(b||1E-6)},length:function(c){var a,b=0,d=l.Tvalues.length;for(a=0;d>a;a++){var h=.5*l.Tvalues[a]+.5;b+=l.Cvalues[a]*l.arcfn(h,c)}return.5*b},map:function(c,a,b,d,h){return d+(c-a)/(b-a)*(h-d)},lerp:function(c,a,b){var d={x:a.x+c*(b.x-a.x),y:a.y+c*(b.y-a.y)};return a.z&&b.z&&(d.z=a.z+c*(b.z-a.z)),d},pointToString:function(c){var a=c.x+"/"+c.y;return"undefined"!=typeof c.z&&(a+="/"+c.z),a},pointsToString:function(c){return"["+
c.map(l.pointToString).join(", ")+"]"},copy:function(c){return JSON.parse(JSON.stringify(c))},angle:function(c,a,b){var d=a.x-c.x;a=a.y-c.y;var h=b.x-c.x;c=b.y-c.y;return u(d*c-a*h,d*h+a*c)},round:function(c,a){var b=""+c,d=b.indexOf(".");return parseFloat(b.substring(0,d+1+a))},dist:function(c,a){var b=c.x-a.x,d=c.y-a.y;return r(b*b+d*d)},closest:function(c,a){var b,d,h=A(2,63);return c.forEach(function(c,f){d=l.dist(a,c);h>d&&(h=d,b=f)}),{mdist:h,mpos:b}},abcratio:function(c,a){if(2!==a&&3!==a)return!1;
if("undefined"==typeof c)c=.5;else if(0===c||1===c)return c;var b=A(c,a)+A(1-c,a);return n((b-1)/b)},projectionratio:function(c,a){if(2!==a&&3!==a)return!1;if("undefined"==typeof c)c=.5;else if(0===c||1===c)return c;var b=A(1-c,a),d=A(c,a)+b;return b/d},lli8:function(c,a,b,d,h,e,f,g){var k=(c-b)*(e-g)-(a-d)*(h-f);return 0==k?!1:{x:((c*d-a*b)*(h-f)-(c-b)*(h*g-e*f))/k,y:((c*d-a*b)*(e-g)-(a-d)*(h*g-e*f))/k}},lli4:function(c,a,b,d){return l.lli8(c.x,c.y,a.x,a.y,b.x,b.y,d.x,d.y)},lli:function(c,a){return l.lli4(c,
c.c,a,a.c)},makeline:function(c,a){var b=w(1),d=c.x,h=c.y,e=a.x,f=a.y,g=(e-d)/3,k=(f-h)/3;return new b(d,h,d+g,h+k,d+2*g,h+2*k,e,f)},findbbox:function(c){var a=k,b=k,d=F,h=F;return c.forEach(function(c){c=c.bbox();a>c.x.min&&(a=c.x.min);b>c.y.min&&(b=c.y.min);d<c.x.max&&(d=c.x.max);h<c.y.max&&(h=c.y.max)}),{x:{min:a,mid:(a+d)/2,max:d,size:d-a},y:{min:b,mid:(b+h)/2,max:h,size:h-b}}},shapeintersections:function(c,a,b,d,h){if(!l.bboxoverlap(a,d))return[];var e=[],f=[b.startcap,b.forward,b.back,b.endcap];
return[c.startcap,c.forward,c.back,c.endcap].forEach(function(a){a.virtual||f.forEach(function(d){if(!d.virtual){var f=a.intersects(d,h);0<f.length&&(f.c1=a,f.c2=d,f.s1=c,f.s2=b,e.push(f))}})}),e},makeshape:function(c,a,b){var d=c.points.length,h=l.makeline(a.points[a.points.length-1],c.points[0]);d=l.makeline(c.points[d-1],a.points[0]);var e={startcap:h,forward:c,back:a,endcap:d,bbox:l.findbbox([h,c,a,d])},f=l;return e.intersections=function(a){return f.shapeintersections(e,e.bbox,a,a.bbox,b)},e},
getminmax:function(c,a,b){if(!b)return{min:0,max:0};var d=k,h=F;-1===b.indexOf(0)&&(b=[0].concat(b));-1===b.indexOf(1)&&b.push(1);for(var e=0,f=b.length;f>e;e++){var g=b[e];g=c.get(g);g[a]<d&&(d=g[a]);g[a]>h&&(h=g[a])}return{min:d,mid:(d+h)/2,max:h,size:h-d}},align:function(c,a){var b=a.p1.x,d=a.p1.y,h=-u(a.p2.y-d,a.p2.x-b);return c.map(function(a){return{x:(a.x-b)*p(h)-(a.y-d)*m(h),y:(a.x-b)*m(h)+(a.y-d)*p(h)}})},roots:function(c,a){a=a||{p1:{x:0,y:0},p2:{x:1,y:0}};var b=c.length-1,d=l.align(c,a),
h=function(a){return 0<=a&&1>=a};if(2===b){b=d[0].y;var e=d[1].y,f=d[2].y,g=b-2*e+f;return 0!==g?(f=-r(e*e-b*f),b=-b+e,[-(f+b)/g,-(-f+b)/g].filter(h)):e!==f&&0===g?[(2*e-f)/2*(e-f)].filter(h):[]}var k,m,n=d[0].y;e=d[1].y;b=d[2].y;g=-n+3*e-3*b+d[3].y;b=(3*n-6*e+3*b)/g;e=(-3*n+3*e)/g;d=(3*e-b*b)/3;var u=d/3;g=(2*b*b*b-9*b*e+n/g*27)/27;e=g/2;n=e*e+u*u*u;if(0>n){var t=-d/3;t=r(t*t*t);var x=-g/(2*t);x=G(-1>x?-1:1<x?1:x);t=2*C(t);return f=t*p(x/3)-b/3,k=t*p((x+D)/3)-b/3,m=t*p((x+2*D)/3)-b/3,[f,k,m].filter(h)}if(0===
n)return x=0>e?C(-e):-C(e),f=2*x-b/3,k=-x-b/3,[f,k].filter(h);f=r(n);return x=C(-e+f),t=C(e+f),[x-t-b/3].filter(h)},droots:function(c){if(3===c.length){var a=c[0],b=c[1],d=c[2];c=a-2*b+d;return 0!==c?(d=-r(b*b-a*d),a=-a+b,[-(d+a)/c,-(-d+a)/c]):b!==d&&0===c?[(2*b-d)/(2*(b-d))]:[]}if(2===c.length)return a=c[0],b=c[1],a!==b?[a/(a-b)]:[]},inflections:function(c){if(4>c.length)return[];var a=l.align(c,{p1:c[0],p2:c.slice(-1)[0]});c=a[2].x*a[1].y;var b=a[3].x*a[1].y,d=a[1].x*a[2].y;a=a[3].x*a[2].y;a=18*
(-3*c+2*b+3*d-a);b=18*(3*c-b-3*d);c=18*(d-c);if(l.approximately(a,0))return!l.approximately(b,0)&&(c=-c/b,0<=c&&1>=c)?[c]:[];c=Math.sqrt(b*b-4*a*c);a*=2;return l.approximately(a,0)?[]:[(c-b)/a,-(b+c)/a].filter(function(a){return 0<=a&&1>=a})},bboxoverlap:function(c,a){var b,d,h,e,f,g=["x","y"],k=g.length;for(b=0;k>b;b++)if(d=g[b],h=c[d].mid,e=a[d].mid,f=(c[d].size+a[d].size)/2,n(h-e)>=f)return!1;return!0},expandbox:function(c,a){a.x.min<c.x.min&&(c.x.min=a.x.min);a.y.min<c.y.min&&(c.y.min=a.y.min);
a.z&&a.z.min<c.z.min&&(c.z.min=a.z.min);a.x.max>c.x.max&&(c.x.max=a.x.max);a.y.max>c.y.max&&(c.y.max=a.y.max);a.z&&a.z.max>c.z.max&&(c.z.max=a.z.max);c.x.mid=(c.x.min+c.x.max)/2;c.y.mid=(c.y.min+c.y.max)/2;c.z&&(c.z.mid=(c.z.min+c.z.max)/2);c.x.size=c.x.max-c.x.min;c.y.size=c.y.max-c.y.min;c.z&&(c.z.size=c.z.max-c.z.min)},pairiteration:function(c,a,b){var d=c.bbox(),h=a.bbox(),e=b||.5;if(d.x.size+d.y.size<e&&h.x.size+h.y.size<e)return[(1E5*(c._t1+c._t2)/2|0)/1E5+"/"+(1E5*(a._t1+a._t2)/2|0)/1E5];c=
c.split(.5);a=a.split(.5);a=[{left:c.left,right:a.left},{left:c.left,right:a.right},{left:c.right,right:a.right},{left:c.right,right:a.left}];a=a.filter(function(a){return l.bboxoverlap(a.left.bbox(),a.right.bbox())});var f=[];return 0===a.length?f:(a.forEach(function(a){f=f.concat(l.pairiteration(a.left,a.right,e))}),f=f.filter(function(a,b){return f.indexOf(a)===b}))},getccenter:function(c,a,b){var d,h=a.x-c.x,e=a.y-c.y,f=b.x-a.x,g=b.y-a.y,k=h*p(y)-e*m(y);h=h*m(y)+e*p(y);e=f*p(y)-g*m(y);f=f*m(y)+
g*p(y);g=(c.x+a.x)/2;var n=(c.y+a.y)/2,r=(a.x+b.x)/2,w=(a.y+b.y)/2;k=l.lli8(g,n,g+k,n+h,r,w,r+e,w+f);h=l.dist(k,c);c=u(c.y-k.y,c.x-k.x);a=u(a.y-k.y,a.x-k.x);b=u(b.y-k.y,b.x-k.x);return b>c?((c>a||a>b)&&(c+=D),c>b&&(d=b,b=c,c=d)):a>b&&c>a?(d=b,b=c,c=d):b+=D,k.s=c,k.e=b,k.r=h,k}};z.exports=l}()},function(z,r,w){!function(){var n=w(2),p=function(m){this.curves=[];this._3d=!1;m&&(this.curves=m,this._3d=this.curves[0]._3d)};p.prototype={valueOf:function(){return this.toString()},toString:function(){return"["+
this.curves.map(function(m){return n.pointsToString(m.points)}).join(", ")+"]"},addCurve:function(m){this.curves.push(m);this._3d=this._3d||m._3d},length:function(){return this.curves.map(function(m){return m.length()}).reduce(function(m,n){return m+n})},curve:function(m){return this.curves[m]},bbox:function(){for(var m=this.curves,p=m[0].bbox(),u=1;u<m.length;u++)n.expandbox(p,m[u].bbox());return p},offset:function(m){var n=[];return this.curves.forEach(function(p){n=n.concat(p.offset(m))}),new p(n)}};
z.exports=p}()}]);
var Snail=function(h,r){function t(a,b,f){var c=0;a.map(function(e,d){var k=new Image;k.onload=function(){b[e[0]]=k;c++;if(c===a.length)return f()};k.src=e[1]})}function n(a){a=a||window.event;if(null==a.pageX&&null!=a.clientX){var b=a.target&&a.target.ownerDocument||document;var c=b.documentElement;b=b.body;a.pageX=a.clientX+(c&&c.scrollLeft||b&&b.scrollLeft||0)-(c&&c.clientLeft||b&&b.clientLeft||0);a.pageY=a.clientY+(c&&c.scrollTop||b&&b.scrollTop||0)-(c&&c.clientTop||b&&b.clientTop||0)}return{x:a.pageX,
    y:a.pageY}}function u(a,b){var f=Math.getMoveAngle(a.x,a.y,b.x,b.y,c.Angle),e=c.ratioMovingAngle.slice(0),d=c.ratioMovingDistance.slice(0),h=0,k=b.x-a.x,v=b.y-a.y,g=Array.apply(null,Array(8)).map(function(a,b){return d[b]*k+c.Position.x}),l=Array.apply(null,Array(8)).map(function(a,b){return d[b]*v+c.Position.y});e=e.map(function(a,b){return e[b]*f});(function w(){1>g.length||window.setTimeout(function(){c.Canvas.style.top=l[0]+"px";c.Canvas.style.left=g[0]+"px";c.Position.x=g[0];c.Position.y=l[0];
    c.Context.clearRect(-1*c.CanvasSize,-1*c.CanvasSize,2*c.CanvasSize,2*c.CanvasSize);c.Context.rotate(e[0]);c.Angle=Math.addDegree(c.Angle,Math.degrees(e[0]));c.Context.drawImage(c.Sprite[h],-10,-10,20,20);g.shift();l.shift();e.shift();h++;w()},50)})()}function p(a,b){c.onMove=!0;(function e(){1>a.length?window.setTimeout(function(){b!==r&&g.remove(b);c.onMove=!1},650):window.setTimeout(function(){u(a[0].p,a[0].Np);a.shift();e()},450)})()}function q(a,b){var f=Math.addDegree(Math.degrees(.5*Math.getMoveAngle(a.x,
    a.y,b.x,b.y,c.Angle)),c.Angle);f=Math.forceFoward(f,Math.sqrt((b.x-a.x)*(b.x-a.x)+(b.y-a.y)*(b.y-a.y)));f=new Bezier(a.x,a.y,a.x+f.x,a.y+f.y,b.x,b.y);var e=f.getLUT(Math.round(.1*(100>f.length()?100:f.length()))),d=[];e.map(function(a,b){if(b<e.length-1){var c={};c.p=e[b];c.Np=e[b+1];d.push(c)}});return d}Math.radians=function(a){return a*Math.PI/180};Math.degrees=function(a){return 180*a/Math.PI};Math.addDegree=function(a,b){var c=a+b;0>c&&(c=360+c);360<c&&(c-=360);return c};Math.getMoveAngle=function(a,
    b,c,e,d){c-=a;e-=b;b=Math.PI/180*d;a=Math.cos(b);b=Math.sin(b);return Math.atan2(a*e-b*c,a*c+b*e)};Math.forceFoward=function(a,b){b*=.666;var c=Math.cos(Math.radians(a))*b,e=Math.sin(Math.radians(a))*b;return{x:c,y:e}};Math.getRadian=function(a,b,c){var e=Math.sqrt(Math.pow(b.x-a.x,2)+Math.pow(b.y-a.y,2));b=Math.sqrt(Math.pow(b.x-c.x,2)+Math.pow(b.y-c.y,2));a=Math.sqrt(Math.pow(c.x-a.x,2)+Math.pow(c.y-a.y,2));return Math.acos((b*b+e*e-a*a)/(2*b*e))};Math.getRange=function(a,b){return Math.sqrt(Math.pow(b.x-
    a.x,2)+Math.pow(b.y-a.y,2))};var g={set:{Canvas:[],feedList:[{},{},{}]}};h.set={Height:0,Width:0,Canvas:null,CanvasSize:40,Context:null,ratioMovingAngle:[.25,.12,.08,.05,.05,.08,.12,.25],ratioMovingDistance:[.05,.1,.2,.4,.75,.85,.94,1],Angle:0,Position:{x:20,y:20},firstMove:!1,onMove:!1,Sprite:null,Images:{},Imageslink:[["Carrot","images/carrot.png"],["Snail0","images/0.png"],["Snail1","images/1.png"],["Snail2","images/2.png"],["Snail3","images/3.png"]]};var c=h.set,d=g.set;g.remove=function(a){d.feedList[a].x=
    !1;d.feedList[a].y=!1;d.Canvas[a].style.top="-100px";d.Canvas[a].style.left="-100px"};g.add=function(a,b){d.feedList[a].x=b.x;d.feedList[a].y=b.y;d.Canvas[a].style.top=d.feedList[a].y+10+"px";d.Canvas[a].style.left=d.feedList[a].x+10+"px"};g.setLocation=function(){document.addEventListener("click",function(a){a=n(a);for(var b=0;b<d.feedList.length;b++)if(!1===d.feedList[b].x){g.add(b,a);break}},!0)};g.init=function(){d.feedList.map(function(a){a.x=!1;a.y=!1;return a})};h.findFeed=function(){var a=
    -1,b=0,f=[0,0,0];(function m(){if(!0===c.onMove)window.setTimeout(m,1E3);else{a=-1;b=9999999;d.feedList.map(function(a,b){f[b]=!1!==a.x?Math.getRange(c.Position,d.feedList[b]):1E7});f.map(function(c,d){c<b&&(b=c,a=d)});if(-1!==a){var g=q(c.Position,d.feedList[a]);p(g,a)}window.setTimeout(m,450)}})()};h.firstMove=function(){document.onmousemove=function(a){!1===c.firstMove&&(a=n(a),a=q(c.Position,a),p(a),c.firstMove=!0)}};h.init=function(){var a=Array.apply(null,Array(4)).map(function(a,b){return c.Images["Snail"+
    b]});c.Height=1024;c.Width=766;c.Canvas=document.getElementById("snail");c.Context=c.Canvas.getContext("2d");c.Context.translate(.5*c.CanvasSize,.5*c.CanvasSize);c.Sprite=a.concat(a.slice(0).reverse());for(a=0;3>a;a++){var b=document.getElementById("carrot"+a),f=b.getContext("2d");d.Canvas.push(b);f.drawImage(c.Images.Carrot,0,0,20,20)}g.init();g.setLocation();h.firstMove();h.findFeed()};h.start=function(){t(c.Imageslink,c.Images,h.init)};return h}(window.Snail||{});Snail.start();